---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Reload systemd daemon
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
