---
- name: Converge
  hosts: all

  roles:
    - role: boutetnico.percona_mysql

      mysql_mysql_native_password: "ON"

      mysql_innodb_numa_interleave: "OFF"

      mysql_load_tz_tables: true

      mysql_databases:
        - name: testdb

      mysql_remove_databases:
        - olddb

      mysql_users:
        - name: test_sha2
          plugin_auth_string: test_sha2
          priv: "*.*:SELECT"
          salt: a90ae3fcf94db9f7538e

        - name: test_native
          password: test_native
          plugin: mysql_native_password
          priv: "*.*:ALL"

      mysql_remove_users:
        - name: olduser
          host: localhost

      mysql_systemd_override:
        Service:
          LimitNOFILE: 65535
