---
- name: Converge
  hosts: all

  roles:
    - role: boutetnico.percona_mysql

      mysql_load_tz_tables: true

      mysql_users:
        - name: test_sha2
          priv: "*.*:SELECT"
          plugin_auth_string: test_sha2
          salt: a90ae3fcf94db9f7538e

        - name: test_native
          priv: "*.*:ALL"
          password: test_native
